### ISSUE TITLE
No way to access restore UI outside of setupwizard

### ISSUE THREAD

**Issue by MadCamel** [seedvault-app/seedvault#85]
There is currently no way I can find to restore a backup outside of the setup wizard. This is an issue because it doesn't allow for alternate methods of moving the backup archives to a new device for restore.

For instance if I have my backups on a server and the only way to get them to the phone is sftp, I am unable to restore these backups. I need to install a sftp client and to do that I've had to complete the setup wizard. Now there is no UI available to restore the backups.

I had to use the "Activity Launcher" application to launch the restore UI.

Perhaps change the Backup settings to Backup/Restore and give an option to launch the restore UI?

Edit: Currently using GrapheneOS. If this is a GrapheneOS specific issue I apologize.

**Comment by grote** [comment]
That's the intended behavior. Access to the restore UI and storage options are configured by the OEM (Graphene) in your case.

Looks like you already found the secret workaround for user's who know what they are doing.

**Comment by chirayudesai** [comment]
In addition to that, restoring an entire backup on an already existing system hasn't been tested, and may or may not cause issues.

Doing it from the SetupWizard is nice because at that point not much is configured, and thus the system can start directly with the restored state.

It could be worthwhile allow selectively restoring via the app's UI too, patches welcome!

**Comment by MadCamel** [comment]
I see. My first instinct with any backup system is to find and validate the restore procedure. Not having a UI or any hints on how to do so really threw me off.

**Comment by r4v3r23** [comment]
> In addition to that, restoring an entire backup on an already existing system hasn't been tested, and may or may not cause issues.
> 
> Doing it from the SetupWizard is nice because at that point not much is configured, and thus the system can start directly with the restored state.
> 
> It could be worthwhile allow selectively restoring via the app's UI too, patches welcome!

i recently successfully restored on an existing system after factory restore.

**Comment by r4v3r23** [comment]
any plans to add the restore on existing install?

**Comment by grote** [comment]
Please see the discussion above: https://github.com/stevesoltys/seedvault/issues/85#issuecomment-629342067

Also restore is accessible already: You can uninstall a backed up app and then install it again, see if the data got restored. Auto Restore needs to be active for this to work.

**Comment by r4v3r23** [comment]
no its not. when you open seedvault on device reset you only see 12 words for new back up

**Comment by grote** [comment]
For documentations' sake, if you know what you are doing and accept the risks, you can start a restore without SetupWizard or debug build with adb:

    adb shell am start-activity -a com.stevesoltys.seedvault.RESTORE_BACKUP

**Comment by trohrt** [comment]
@grote bless you, i was struggling all day trying to get that going!!! a backup manager of some sort needs to be implemented

**Comment by gked** [comment]
@grote if this is a by design behavior, can we at least have a message on SeedVaultApp on how one should go about restoring their backup?

**Comment by grote** [comment]
@gked This is **not** a Seedvault issue. The OEM (or integrator) needs to ensure that apps that it allows for backup (see [`config.xml`](https://github.com/seedvault-app/seedvault/blob/d53f0fcde2202b79f83d7b77817e1face6c98e13/app/src/main/res/values/config.xml)), are available when restoring. Also, OEMs can decide to make restore available outside of SetupWizard as well. This is all configurable in Seedvault since first release.

**Comment by grote** [comment]
@gked dedicated ticket about the issue you might be having: https://github.com/seedvault-app/seedvault/issues/251

**Comment by danwdart** [comment]
This command does not start the restore on version 2021.07.26.20... anything else?

**Comment by MadCamel** [comment]
> This command does not start the restore on GrapheneOS version 2021.07.26.20... anything else?

Are you using GrapheneOS? From the changelog:
`Seedvault: switch to GrapheneOS fork with intent access restricted to prevent other apps from spawning the activities;`

I'm not sure why they'd do this as now I cannot restore my backups but yeah, I'm in the same boat.

**Comment by grote** [comment]
this was submitted for upstream inclusion btw.: #287

**Comment by flawedworld** [comment]
Hi @MadCamel @danwdart, I am sorry to hear you were unable to restore your backups, we were not aware of anyone reporting issues on the issue tracker for GrapheneOS or in the testing room so we (wrongly) assumed nobody was impacted negatively. I will make sure it is resolved for you both. Apologies for the inconvenience.

**Comment by rugk** [comment]
BTW this seems to be already implemented/CustomROM maintainers could enable it when bundling the app, see:
https://github.com/seedvault-app/seedvault/blob/acc332b0fdd36823332f7d003adf80bc49378027/app/src/main/res/values/config.xml#L11

**Comment by rugk** [comment]
BTW here is the downstream discussion/issue at LineageOS about essentially the same issue:
https://gitlab.com/LineageOS/issues/android/-/issues/3008

**Comment by flawedworld** [comment]
#78 should be taken into consideration before an operating system bundling seedvault enables the option in settings.

**Comment by flawedworld** [comment]
@MadCamel @danwdart A fix for this will be shipped in the next GrapheneOS release. We didn't originally allow this due to it being a UserManager restriction bypass. We have now got an appropriate fix downstream for which we need to fix unit tests for in order for it to be accepted upstream.

**Comment by flawedworld** [comment]
This is now resolved in the 2021090819 release of GrapheneOS. Any further issues please let me know.

**Comment by rugk** [comment]
Thew newly published release [v11-2.2[](https://github.com/seedvault-app/seedvault/releases/tag/11-2.2) states:

> Allow launching restore through a dialer code

Soo, now we only need to know which dialer code that is… :sweat_smile: 

So, could you please document it somewhere? Maybe in the wiki?

**Comment by chirayudesai** [comment]
I updated the 11-2.2 release notes to mention the code.

Also mentioning it here: `*#*#RESTORE#*#*` aka `*#*#7378673#*#*`

**Comment by rugk** [comment]
> I updated the 11-2.2 release notes to mention the code.

Note that I'd argue that this is still not enough, because information in release notes tend to get lost – 10 releases away or so.

I would add it to the FAQ myself, if I could edit or, but well…
…so let's propose the following FAQ:
> **How can I trigger the restore UI after initial device installation??**
> Note that this is a **experimental feature** you are trying to do trigger here. Remember that if you have the “auto restore” feature enabled, app data for newly installed apps get's automatically restored, which may be a working alternative for your feature.  
> To be clear, restoring an entire backup on an already existing system has not been tested thoroughly, and may or may not cause issues on the device you are running on. Whether it works may also depend on how “fresh” the Android installation still is.
>
> If you anyway want to use that feature and trigger a full system restore after installation, you can use the secret dialer code (go to your dialer app and type them in) `*#*#7378673#*#*`, which you can type as the [vanity number](https://en.wikipedia.org/wiki/Phoneword) `*#*#RESTORE#*#*` by typing the letters in your dialer.

**Comment by Natorator** [comment]
My main concern with this issue is that I have not had an opportunity to encrypt my phone's storage until after the only opportunity to restore my backed-up data has passed. There may only be a brief period between restore and encryption during which my data is unencrypted on the device, if I remember to encrypt the storage as the first thing - but that might not be acceptable for the paranoid.

**Comment by rugk** [comment]
> My main concern with this issue is that I have not had an opportunity to encrypt my phone's storage until after the only opportunity to restore my backed-up data has passed. 

Hmm, all moderately modern phones and Android versions do have encryption setup by default, so you should not need to setup that manually? :thinking:

**Comment by Natorator** [comment]
I'm on a Samsung Galaxy S5, which is an old phone, but I'm installing a LineageOS 18.1 build from last week. After a full factory reset, "not encrypted" is definitely the default state after completing the setup wizard.

**Comment by rugk** [comment]
Yeah it more depends on the phone and whether it was encrypted before than what OS you install. But yay… it's kinda off-topic anyway.

**Comment by Entreprenerdz** [comment]
Let me see if I have this right.  Restore feature has hidden access so no one can test/plan on how to restore.  Restore only accessible after you factory reset.  Factory reset wipes all backups off your device.  Have I missed anything?  Oh, is there a standard location or filename for the backup?  I have 256GB of storage yet I've never seen anything large rolling over my sync software.  It might be good to know where it was before it got wiped off.  System data files, inaccessible to most?

Alright... there's my gripe for the year.  This phone's been driving me nuts the past 3 weeks, double adb connection or 0, infinite loop trying to reconnect even though it's connected, sip phone service won't work because of that.  Phone calls come in but I can't answer them, can't call out.  Whew... and that'll take care of my whine for the year.  I was afraid I was gonna let those go to waste.

Anyone have any info for me that might get me the turkey and be pleasantly surprised for the year?

**Comment by jtagcat** [comment]
Hey, could we document these somewhere visible? What warning is needed?

I've come searching for this issue for the 4th or 5th time. Yes, I should've bookmarked it.

*#*#RESTORE#*#* aka *#*#7378673#*#* or `adb shell am start-activity -a com.stevesoltys.seedvault.RESTORE_BACKUP`

or something to the README?

**Comment by grote** [comment]
Added to the FAQ: https://github.com/seedvault-app/seedvault/wiki/FAQ#how-to-restore-after-passing-through-setup-wizard

Thanks @rugk!

**Comment by beckietech** [comment]
Dear @MadCamel,

I am new to this project and I'm facing lacking of main activity and launcher from manifest.xml. Is there any clue to find out that? Thank you in adv.

**Comment by Rahoon-GOAWAY** [comment]
Hey @MadCamel, I've found another work around, since the dialer code didn't work for me either. You could try this if you still haven't managed to restore yours, though it's been some time since you posted.

Phone: Pixel 4a, Android 12, Graphene OS

## Procedure
1. Turn on phone, don't start the setup yet. Press the power button to turn the screen off.
2. Plug the phone into the computer, the notification for a connected device should pop up on the 'lock screen'
3. Tap the notification, select "file transfer"
4. From the computer, make a folder in the phone's shared storage folder called `.SeedVaultAndroidBackup`
5. Copy/move the backup files into `.SeedVaultAndroidBackup`
6. After the transfer is complete, unplug the phone
7. Start the setup process, and follow the restoration wizard, it should work as normal

## Notes:
- I did this whole thing in a separate user profile created to test this. It didn't have any contacts or SMS data, I don't know if those get restored
- Apps were reinstalled and configured correctly, but I had very few to back up in the first place. As I said, this was a test profile, so not much was there.
- files were **NOT** restored, but I understand that storage backup is still experimental at the moment? If you do this, make sure to back up your files elsewhere.

## New note/update
- tried this again on a different profile and the files were restored too. My PC did lose power in the middle of the first time copying the files over, so I guess it was just something to do with that.

**Comment by DurvalMenezes** [comment]
Is there a way to restore just a single app (apk *and* all its data), instead of all apps?

**Comment by rugk** [comment]
> Is there a way to restore just a single app (apk and all its data),

If you have the auto-restore options enabled in the settings that is what should happen when you install an app that has data. AFAIk.

**Comment by mnlipp** [comment]
I've thought a long time about adding this here, but it was the best match when searching so maybe it saves someone some time.

Backup with lineageos 18 (nothing newer for my device available) and nextcloud.

* Restore during setup does not work, because it want's to install NextCloud (sounds great, but isn't) and hangs in "Downloading" in Google Play forever.

* Restore after setup (aka `*#*#7378673#*#*`) does not work because my device is a tablet without phone, so dialers simply crash.

* `adb shell am start-activity -a com.stevesoltys.seedvault.RESTORE_BACKUP` does not work, something about "intend not found"

* "Simple" copy before setup does not work, because the directory made available by the device via mtp is read-only.

Finally:

Boot to recovery before setup, mount data partition, copy backup from nextcloud to device with adb (luckily there's enough storage), reboot. (Took me a day in total to find out.)

Finally, don't forget to change settings: use Google for backup!

**Comment by DDvO** [comment]
I need such a workaround as well because on my new phone (where I want to restore data from my old phone), even with the latest LineageOS 21.0, which is supposed to support Seedvault since long, access to my webDAV server does not work out of the box:
* The direct method fails because my HTTPS server certificate is not generally trusted and I could not find a way of installing the trust anchor certificate beforehand.
* The DAVx5 app, which is able to cope with the untrusted server cert, is not pre-installed.
I've filed a bug report on that: #683.

After manually installing (via ADB) the DAVx5 app, I was able to 
use `adb root` followed by `adb shell am start-activity -a com.stevesoltys.seedvault.RESTORE_BACKUP`

Yet in the end, after the server was accessed successfully, 
the restore attempt got stuck with `No suitable backups found at given location`  :-(
although the backup data of my old phone on the server was freshly generated 
and I used on my new phone the correct 12-word passphrase from my old phone.
I've filed a bug report on that: #682.

BTW, already the backup process does not work for most apps+data (see #684) 
and appears pretty inefficient (see #685).

Given all these major issues making Seedvault useless, I am deeply disappointed with it.

**Comment by DDvO** [comment]
BTW, in order to be able to enter the existing 12-word passphrase of the backup data to be restored, do not attempt to set up Seedvault backup in the system settings on the new system where you want to restore the backup, as otherwise a new unsuitable passphrase is generated automatically.

In case you accidentally did so, this data can be cleared by entering the settings, choose Apps and "See all apps", enable "Show system (apps)" in the top-right menu, select the Seedvault app, and clear its storage (and cache).

**Comment by julianfoad** [comment]
Related: #671 "Allow restore after device set-up" proposes a robust, user-visible solution.
